export const data = [
   {
      "id": 1,
      "make": "Toyota",
      "model": "Camry",
      "year": 2022,
      "seat": 5,
      "price": 25000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "25 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "203 hp",
      "image1": require("./../assets/CompareImage/HondaCamery.jpg"),
      "image2": require("./../assets/CompareImage/HondaCamery.jpg"),
      "image3": require("./../assets/CompareImage/HondaCamery.jpg"),
      "tag": "discount",
   },
   {
      "id": 2,
      "make": "Honda",
      "model": "Civic",
      "year": 2021,
      "seat": 5,
      "price": 22000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "30 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "158 hp",
      "image1": require("./../assets/CompareImage/HondaCivic.jpg"),
      "image2": require("./../assets/CompareImage/HondaCivic.jpg"),
      "image3": require("./../assets/CompareImage/HondaCivic.jpg"),
      "tag": "normal",
   },
   {
      "id": 3,
      "make": "Ford",
      "model": "Focus",
      "year": 2023,
      "seat": 4,
      "price": 23000,
      "engineType": "Inline-3",
      "fuelType": "Gasoline",
      "mileage": "28 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "123 hp",
      "image1": require("./../assets/CompareImage/FordFocus.jpg"),
      "image2": require("./../assets/CompareImage/FordFocus.jpg"),
      "image3": require("./../assets/CompareImage/FordFocus.jpg"),
      "tag": "discount",
   },
   {
      "id": 4,
      "make": "Chevrolet",
      "model": "Cruze",
      "year": 2022,
      "seat": 5,
      "price": 21000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "32 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "153 hp",
      "image1": require("./../assets/CompareImage/ChervroletCruze.jpg"),
      "image2": require("./../assets/CompareImage/ChervroletCruze.jpg"),
      "image3": require("./../assets/CompareImage/ChervroletCruze.jpg"),
      "tag": "normal",
   },
   {
      "id": 5,
      "make": "Nissan",
      "model": "Sentra",
      "year": 2020,
      "seat": 5,
      "price": 20000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "29 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "149 hp",
      "image1": require("./../assets/CompareImage/NissanSentra.jpg"),
      "image2": require("./../assets/CompareImage/NissanSentra.jpg"),
      "image3": require("./../assets/CompareImage/NissanSentra.jpg"),
      "tag": "normal",
   },
   {
      "id": 6,
      "make": "BMW",
      "model": "5 Series",
      "year": 2022,
      "seat": 6,
      "price": 45000,
      "engineType": "Inline-6",
      "fuelType": "Gasoline",
      "mileage": "27 mpg",
      "transmission": "Automatic",
      "driveTrain": "Rear-Wheel Drive",
      "power": "335 hp",
      "image1": require("./../assets/CompareImage/BMW5S.jpg"),
      "image2": require("./../assets/CompareImage/BMW5S.jpg"),
      "image3": require("./../assets/CompareImage/BMW5S.jpg"),
      "tag": "discount",
   },
   {
      "id": 7,
      "make": "Mercedes-Benz",
      "model": "E-Class",
      "year": 2021,
      "seat": 5,
      "price": 50000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "26 mpg",
      "transmission": "Automatic",
      "driveTrain": "Rear-Wheel Drive",
      "power": "255 hp",
      "image1": require("./../assets/CompareImage/MercesdezEclass.jpg"),
      "image2": require("./../assets/CompareImage/MercesdezEclass.jpg"),
      "image3": require("./../assets/CompareImage/MercesdezEclass.jpg"),
      "tag": "discount",
   },
   {
      "id": 8,
      "make": "Audi",
      "model": "A6",
      "year": 2023,
      "seat": 3,
      "price": 48000,
      "engineType": "V6",
      "fuelType": "Gasoline",
      "mileage": "25 mpg",
      "transmission": "Automatic",
      "driveTrain": "All-Wheel Drive",
      "power": "335 hp",
      "image1": require("./../assets/CompareImage/AudiA6.jpg"),
      "image2": require("./../assets/CompareImage/AudiA6.jpg"),
      "image3": require("./../assets/CompareImage/AudiA6.jpg"),
      "tag": "discount",
   },
   {
      "id": 9,
      "make": "Tesla",
      "model": "Model S",
      "year": 2022,
      "seat": 5,
      "price": 80000,
      "engineType": "Electric",
      "fuelType": "Electric",
      "mileage": "396 miles per charge",
      "transmission": "Automatic",
      "driveTrain": "All-Wheel Drive",
      "power": "Dual Motors",
      "image1": require("./../assets/CompareImage/TeslaS.jpg"),
      "image2": require("./../assets/CompareImage/TeslaS.jpg"),
      "image3": require("./../assets/CompareImage/TeslaS.jpg"),
      "tag": "normal",
   },
   {
      "id": 10,
      "make": "Volkswagen",
      "model": "Jetta",
      "year": 2021,
      "seat": 5,
      "price": 23000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "30 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "147 hp",
      "image1": require("./../assets/CompareImage/VolSwa.jpeg"),
      "image2": require("./../assets/CompareImage/VolSwa.jpeg"),
      "image3": require("./../assets/CompareImage/VolSwa.jpeg"),
      "tag": "normal",
   },
   {
      "id": 11,
      "make": "Hyundai",
      "model": "Elantra",
      "year": 2023,
      "seat": 5,
      "price": 24000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "33 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "147 hp",
      "image1": require("./../assets/CompareImage/HyunDaiE.jpg"),
      "image2": require("./../assets/CompareImage/HyunDaiE.jpg"),
      "image3": require("./../assets/CompareImage/HyunDaiE.jpg"),
      "tag": "normal",
   },
   {
      "id": 12,
      "make": "Kia",
      "model": "Soul",
      "year": 2020,
      "seat": 5,
      "price": 20000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "29 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "147 hp",
      "image1": require("./../assets/CompareImage/KiaSoul.jpg"),
      "image2": require("./../assets/CompareImage/KiaSoul.jpg"),
      "image3": require("./../assets/CompareImage/KiaSoul.jpg"),
      "tag": "normal",
   },
   {
      "id": 13,
      "make": "Subaru",
      "model": "Forester",
      "year": 2022,
      "seat": 5,
      "price": 28000,
      "engineType": "Boxer-4",
      "fuelType": "Gasoline",
      "mileage": "26 mpg",
      "transmission": "Automatic",
      "driveTrain": "All-Wheel Drive",
      "power": "182 hp",
      "image1": require("./../assets/CompareImage/Subaru.jpg"),
      "image2": require("./../assets/CompareImage/Subaru.jpg"),
      "image3": require("./../assets/CompareImage/Subaru.jpg"),
      "tag": "normal",
   },
   {
      "id": 14,
      "make": "Mazda",
      "model": "CX-5",
      "year": 2021,
      "seat": 5,
      "price": 26000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "28 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "187 hp",
      "image1": require("./../assets/CompareImage/MazdaCX5.jpg"),
      "image2": require("./../assets/CompareImage/MazdaCX5.jpg"),
      "image3": require("./../assets/CompareImage/MazdaCX5.jpg"),
      "tag": "normal",
   },

   {
      "id": 15,
      "make": "Ford",
      "model": "Escape",
      "year": 2023,
      "seat": 5,
      "price": 27000,
      "engineType": "Hybrid",
      "fuelType": "Gasoline",
      "mileage": "41 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "165 hp",
      "image1": require("./../assets/CompareImage/fordEscape.jpg"),
      "image2": require("./../assets/CompareImage/fordEscape.jpg"),
      "image3": require("./../assets/CompareImage/fordEscape.jpg"),
      "tag": "discount",
   },
   {
      "id": 16,
      "make": "Chevrolet",
      "model": "Equinox",
      "year": 2022,
      "seat": 5,
      "price": 26000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "28 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "170 hp",
      "image1": require("./../assets/CompareImage/chevroletEquinow.jpg"),
      "image2": require("./../assets/CompareImage/chevroletEquinow.jpg"),
      "image3": require("./../assets/CompareImage/chevroletEquinow.jpg"),
      "tag": "discount",
   },
   {
      "id": 17,
      "make": "Nissan",
      "model": "Rogue",
      "year": 2020,
      "seat": 5,
      "price": 25000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "29 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "170 hp",
      "image1": require("./../assets/CompareImage/nissanRouge.jpg"),
      "image2": require("./../assets/CompareImage/nissanRouge.jpg"),
      "image3": require("./../assets/CompareImage/nissanRouge.jpg"),
      "tag": "discount",
   },
   {
      "id": 18,
      "make": "BMW",
      "model": "X3",
      "year": 2022,
      "seat": 5,
      "price": 48000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "26 mpg",
      "transmission": "Automatic",
      "driveTrain": "All-Wheel Drive",
      "power": "248 hp",
      "image1": require("./../assets/CompareImage/bmwX3.jpg"),
      "image2": require("./../assets/CompareImage/bmwX3.jpg"),
      "image3": require("./../assets/CompareImage/bmwX3.jpg"),
      "tag": "discount",
   },
   {
      "id": 19,
      "make": "Mercedes-Benz",
      "model": "GLC",
      "year": 2021,
      "seat": 5,
      "price": 52000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "24 mpg",
      "transmission": "Automatic",
      "driveTrain": "Rear-Wheel Drive",
      "power": "255 hp",
      "image1": require("./../assets/CompareImage/mercedes-benzGlc.jpg"),
      "image2": require("./../assets/CompareImage/mercedes-benzGlc.jpg"),
      "image3": require("./../assets/CompareImage/mercedes-benzGlc.jpg"),
      "tag": "discount",
   },
   {
      "id": 20,
      "make": "Audi",
      "model": "Q5",
      "year": 2023,
      "seat": 5,
      "price": 50000,
      "engineType": "V6",
      "fuelType": "Gasoline",
      "mileage": "23 mpg",
      "transmission": "Automatic",
      "driveTrain": "All-Wheel Drive",
      "power": "349 hp",
      "image1": require("./../assets/CompareImage/audiQ5.jpg"),
      "image2": require("./../assets/CompareImage/audiQ5.jpg"),
      "image3": require("./../assets/CompareImage/audiQ5.jpg"),
      "tag": "discount",
   },
   {
      "id": 21,
      "make": "Toyota",
      "model": "RAV4",
      "year": 2022,
      "seat": 5,
      "price": 27000,
      "engineType": "Inline-4",
      "fuelType": "Gasoline",
      "mileage": "30 mpg",
      "transmission": "Automatic",
      "driveTrain": "Front-Wheel Drive",
      "power": "203 hp",
      "image1": require("./../assets/CompareImage/ToyotaRAV4.jpg"),
      "image2": require("./../assets/CompareImage/ToyotaRAV4.jpg"),
      "image3": require("./../assets/CompareImage/ToyotaRAV4.jpg"),
      "tag": "discount",
   }

];
